const data =
  {descriptions: ["Rated Top Five in the U.S. by the Zagat Guide, named one of America's top Steakhouses by the Knife & Fork Club, Men's Journal & the Independent Cattleman's Association, & a perennial winner of newspaper & magazine reader polls, Manny's commands a fanatical local following & a national reputation.", "Join us for breakfast, lunch, dinner or drinks 7 days a week, and enjoy REAL food, not fancy contraptions...described by food writers as 'unique but not fancy; interesting but not fussy'. Almost everything is made from scratch, from our award-winning peanut butter to even housemade ketchup...winning us over 67 'best' awards as well as accolades in Gourmet Magazine, Conde Nast Traveler, Midwest Living and other national magazines.", "Enjoy our gourmet Market Table, authentic Brazilian side dishes, and award-winning wine list. Guests can also choose to enjoy lighter seafood selections or enjoy the gourmet Market Table only option. We also offer semiprivate and private areas that can accommodate parties up to 140.", "We serve simple, fresh Italian cuisine made from local ingredients. Our handcrafted meals accompany a thoughtful, approachable wine selection. We believe dining is more than a menu: it is an experience, and ours is quality. When you’re our guest, our staff learn your name and remember your favorite glass of wine. We passionately commit to bring you the full dining experience – quality food and wine presented with welcoming service. Every meal. Every day. Please join us.", "Sip a cocktail in the lounge, take a seat at our grand oyster bar, or kick back in a horseshoe booth before diving into a sea of Ultra-Fresh fish, including steak-cut Alaskan halibut, seasonal favorites like fresh Copper River salmon or hard-to-find delicacies like true Dover sole or bluefin tuna. Our knowledgeable staff will delight you with exceptional service — guiding you through the wide variety of items on our menu and helping you select the perfect wine to complement your meal.", "A cozy spot with an extensive menu, full bar and a wine list of extraordinary value. The featured entrees are prepared on our custom designed charcoal grill. This giant grill sears your order to juicy perfection. Open seven nights a week, with Sunday Brunch 10am - 2pm"],
  ratings: function getRatings() {return (Math.random() * (5 - 0) + 0).toFixed(1);},
  reviews: function getReviews() {return Math.floor(Math.random() * Math.floor(1200));},
  maxPrice: function getMaxPrice() {return '$' + Math.floor(Math.random() * Math.floor(120))},
  foodType: ["Mexican", "Liberian", "American", "Comfort Food", "Chinese", "Ecuadorian"],
  tag1: ['modern', 'contemporary', 'good for dates', "special occasions", "business meals"],
  tag2: ['local meals', 'casual', 'neighborhood gem', 'fancy', 'creative cuisine'],
  tag3: ['fit for foodies', 'scenic view', 'good for anniversaries', 'romantic', 'fun'] };

module.exports = data;